# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd45e2c2ee212990e4592003f0b4cb332f37b0879dd59fe024373e4dfc467b867029d4168668bf801b24cc88e37b67d6a0fad664a733ea70a90e127c680a2c69

test:
  secret_key_base: f946f494c84c6003cca42a8b788af9d11171e54948e924ff0bbd11a18d92ea8c75a7438e9858281259fe83aa312f02a6e466fde28d1d40cc64abd8dde3f8304d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
